DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (SEQ INT PRIMARY KEY AUTO_INCREMENT, ID VARCHAR, NAME VARCHAR);

INSERT INTO USERS (ID, NAME) VALUES ('godseop', '임행섭');
INSERT INTO USERS (ID, NAME) VALUES ('springboot', '스프링부트');
INSERT INTO USERS (ID, NAME) VALUES ('maven', '메이븐');
INSERT INTO USERS (ID, NAME) VALUES ('mybatis', '마이바티스');